import React, { Component } from 'react';
import './App.css';
import 'prismjs';
import 'prismjs/themes/prism.css';

class App extends Component {

  constructor() {
    super();
    this.state = {
      strict: true,
      es6: false,
      imports: [
        {
          'variable': 'gulp',
          'npm': 'gulp'
        },
        {
          'variable': 'concat',
          'npm': 'gulp-concat'
        },
        {
          'variable': 'sass',
          'npm': 'gulp-sass'
        },
        {
          'variable': 'uglify',
          'npm': 'gulp-uglify'
        },
        {
          'variable': 'browserSyncLib',
          'npm': 'browser-sync'
        }
      ]
    }
  }

  renderStrict() {
    return this.state.strict ? `'use strict';` : '';
  }

  renderImports() {
    let imports = '';
    this.state.imports.forEach((module, index, array) => {
      if (this.state.es6) {
        imports += `var ${module.variable} = require'${module.npm}');\n`;
      } else {
        imports += `import ${module.variable} from '${module.npm}';\n`;
      }
    });
    return imports.slice(0, -1);
  }

  // Terrible indentation is a requirement for <pre><code> to output properly
  render() {
    return (
      <div className="App">
        <span>package.json</span>
        <pre><code className="language-json">{`{
  "name": "Project Name",
  "version": "1.0.0",
  "description": "Generated by https://github.com/mjlai3/gulpfile-generator",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "browser-sync": "^2.23.6",
    "gulp": "^3.9.1",
    "gulp-concat": "^2.6.1",
    "gulp-sass": "^3.1.0",
    "gulp-uglify": "^3.0.0",
    "vinyl-buffer": "^1.0.1",
    "vinyl-source-stream": "^2.0.0"
  }
        }`}</code></pre>
        <span>gulpfile.js</span>
        <pre><code className="language-javascript">{`${this.renderStrict()}

${this.renderImports()}
        `}</code></pre>
      </div>
    );
  }
}

export default App;
